language: generic

matrix:
  fast_finish: true

  include:
  - os: linux
    sudo: false
    python: 2.7
    compiler: gcc

  - os: linux
    sudo: false
    python: 3.5
    compiler: gcc

  - os: osx
    python: 2.7
    env:
      - CFLAGS="-m64"
      - LDFLAGS="-m64"

  - os: osx
    python: 3.5
    env:
      - CFLAGS="-m64"
      - LDFLAGS="-m64"

  - os: osx
    python: 2.7
    compiler: clang
    env:
      - CC="clang"
      - CFLAGS="-arch x86_64"
      - LDFLAGS="-arch x86_64"

  - os: osx
    python: 3.5
    compiler: clang
    env:
      - CC="clang"
      - CFLAGS="-arch x86_64"
      - LDFLAGS="-arch x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CONDA_INSTALLER=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CONDA_INSTALLER=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - wget $CONDA_INSTALLER
  - bash Miniconda3-latest-*.sh -b -p /tmp/miniconda3
  - export PATH=/tmp/miniconda3/bin:$PATH

install:
  - conda install --yes gcc
  - ./waf configure --prefix=/tmp/hstcal
  - ./waf build
  - ./waf install

